stages:
  - fake
  - app_build
  - server_build
  - deploy

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_BRANCH

.if-mr-to-dev-main: &if-mr-to-dev-main
  if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_BRANCH'

include:
  - local: .gitlab/ci/backend.gitlab-ci.yml
    rules:
      - <<: *if-mr-to-dev-main
      - when: never
fake_job:
  stage: fake
  script: echo
  rules:
    - if: $EMPTY_VAR