// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ZMovie.Infrastructure.Analytics.Persistence;

#nullable disable

namespace ZMovie.Infrastructure.Analytics.Persistence.Migrations
{
    [DbContext(typeof(AnalyticsDbContext))]
    [Migration("20260831125504_AnalyticsInitial")]
    partial class AnalyticsInitial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ZMovie.Domain.Analytics.TitleViewEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("EpisodeNumber")
                        .HasColumnType("integer")
                        .HasColumnName("episode_number");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("session_id");

                    b.Property<Guid>("TitleId")
                        .HasColumnType("uuid")
                        .HasColumnName("title_id");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("ViewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("viewed_at");

                    b.HasKey("Id")
                        .HasName("pk_title_view_events");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_title_view_events_session_id");

                    b.HasIndex("TitleId")
                        .HasDatabaseName("ix_title_view_events_title_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_title_view_events_user_id");

                    b.HasIndex("ViewedAt")
                        .HasDatabaseName("ix_title_view_events_viewed_at");

                    b.ToTable("title_view_events", "public");
                });
#pragma warning restore 612, 618
        }
    }
}
