// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ZMovie.Infrastructure.Engagement.Persistence;

#nullable disable

namespace ZMovie.Infrastructure.Engagement.Persistence.Migrations
{
    [DbContext(typeof(EngagementDbContext))]
    [Migration("20260831125500_EngagementInitial")]
    partial class EngagementInitial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ZMovie.Domain.Engagement.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("author_name");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("comment");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.Property<Guid>("TitleId")
                        .HasColumnType("uuid")
                        .HasColumnName("title_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_title_reviews");

                    b.HasIndex("TitleId", "UpdatedAt")
                        .HasDatabaseName("ix_title_reviews_title_id_updated_at");

                    b.HasIndex("TitleId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_title_reviews_title_id_user_id");

                    b.ToTable("title_reviews", "public");
                });

            modelBuilder.Entity("ZMovie.Domain.Engagement.SavedTitle", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("TitleId")
                        .HasColumnType("uuid")
                        .HasColumnName("title_id");

                    b.Property<DateTimeOffset>("SavedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("saved_at");

                    b.HasKey("UserId", "TitleId")
                        .HasName("pk_saved_titles");

                    b.HasIndex("TitleId")
                        .HasDatabaseName("ix_saved_titles_title_id");

                    b.HasIndex("UserId", "SavedAt")
                        .HasDatabaseName("ix_saved_titles_user_id_saved_at");

                    b.ToTable("saved_titles", "public");
                });

            modelBuilder.Entity("ZMovie.Domain.Engagement.WatchProgress", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("PlayableId")
                        .HasColumnType("uuid")
                        .HasColumnName("playable_id");

                    b.Property<int?>("EpisodeNumber")
                        .HasColumnType("integer")
                        .HasColumnName("episode_number");

                    b.Property<double>("Position")
                        .HasColumnType("double precision")
                        .HasColumnName("progress_seconds");

                    b.Property<Guid>("TitleId")
                        .HasColumnType("uuid")
                        .HasColumnName("title_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId", "PlayableId")
                        .HasName("pk_watch_history");

                    b.HasIndex("TitleId")
                        .HasDatabaseName("ix_watch_history_title_id");

                    b.HasIndex("UserId", "UpdatedAt")
                        .HasDatabaseName("ix_watch_history_user_id_updated_at");

                    b.HasIndex("UserId", "TitleId", "UpdatedAt")
                        .HasDatabaseName("ix_watch_history_user_id_title_id_updated_at");

                    b.ToTable("watch_history", "public");
                });
#pragma warning restore 612, 618
        }
    }
}
