// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ZMovie.Infrastructure.Personalization.Persistence;

#nullable disable

namespace ZMovie.Infrastructure.Personalization.Persistence.Migrations
{
    [DbContext(typeof(PersonalizationDbContext))]
    [Migration("20260831125508_PersonalizationInitial")]
    partial class PersonalizationInitial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ZMovie.Domain.Personalization.AssistantLearningEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("event_type");

                    b.Property<string>("Features")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("features");

                    b.Property<int>("Rank")
                        .HasColumnType("integer")
                        .HasColumnName("rank");

                    b.Property<Guid>("RecommendationId")
                        .HasColumnType("uuid")
                        .HasColumnName("recommendation_id");

                    b.Property<double>("Reward")
                        .HasColumnType("double precision")
                        .HasColumnName("reward");

                    b.Property<Guid>("TitleId")
                        .HasColumnType("uuid")
                        .HasColumnName("title_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_assistant_learning_events");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("ix_assistant_learning_events_user_id_created_at");

                    b.HasIndex("UserId", "RecommendationId", "TitleId")
                        .HasDatabaseName("ix_assistant_learning_events_user_id_recommendation_id_title_id");

                    b.ToTable("assistant_learning_events", "public");
                });
#pragma warning restore 612, 618
        }
    }
}
